spring:
  application:
    name: aurora-springboot
  profiles:
    active: prod
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  threads:
    virtual:
      enabled: true
  datasource:
    hikari:
      minimum-idle: 10
      idle-timeout: 180000
      maximum-pool-size: 100
      auto-commit: true
      pool-name: Aurora-HikariPool
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      register-mbeans: true

management:
  server:
    port: 9616
  endpoints:
    web:
      exposure:
        include: 'prometheus, health, info'
  metrics:
    tags:
      application: "aurora-springboot"