/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./components/ArticleCard/src/ArticleCard.vue')['default']
    AuroraNavigator: typeof import('./components/AuroraNavigator.vue')['default']
    Avatar: typeof import('./components/Avatar.vue')['default']
    Breadcrumb: typeof import('./components/Breadcrumb.vue')['default']
    Comment: typeof import('./components/Comment/src/Comment.vue')['default']
    CommentForm: typeof import('./components/Comment/src/CommentForm.vue')['default']
    CommentItem: typeof import('./components/Comment/src/CommentItem.vue')['default']
    CommentList: typeof import('./components/Comment/src/CommentList.vue')['default']
    CommentReplyForm: typeof import('./components/Comment/src/CommentReplyForm.vue')['default']
    CommentReplyItem: typeof import('./components/Comment/src/CommentReplyItem.vue')['default']
    Controls: typeof import('./components/Header/src/Controls.vue')['default']
    Dia: typeof import('./components/Dia.vue')['default']
    Dropdown: typeof import('./components/Dropdown/src/Dropdown.vue')['default']
    DropdownItem: typeof import('./components/Dropdown/src/DropdownItem.vue')['default']
    DropdownMenu: typeof import('./components/Dropdown/src/DropdownMenu.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Feature: typeof import('./components/Feature/src/Feature.vue')['default']
    FeatureList: typeof import('./components/Feature/src/FeatureList.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header/src/Header.vue')['default']
    HorizontalArticle: typeof import('./components/ArticleCard/src/HorizontalArticle.vue')['default']
    Logo: typeof import('./components/Header/src/Logo.vue')['default']
    MobileMenu: typeof import('./components/MobileMenu.vue')['default']
    Navigation: typeof import('./components/Header/src/Navigation.vue')['default']
    Navigator: typeof import('./components/Sidebar/src/Navigator.vue')['default']
    Notice: typeof import('./components/Sidebar/src/Notice.vue')['default']
    OauthLogin: typeof import('./components/OauthLogin.vue')['default']
    Paginator: typeof import('./components/Paginator.vue')['default']
    Profile: typeof import('./components/Sidebar/src/Profile.vue')['default']
    RecentComment: typeof import('./components/Sidebar/src/RecentComment.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchModel: typeof import('./components/SearchModel.vue')['default']
    Sidebar: typeof import('./components/Sidebar/src/Sidebar.vue')['default']
    Skeleton: typeof import('./components/LoadingSkeleton/src/Skeleton.vue')['default']
    SkeletonTheme: typeof import('./components/LoadingSkeleton/src/SkeletonTheme.vue')['default']
    Social: typeof import('./components/Social.vue')['default']
    Sticky: typeof import('./components/Sticky.vue')['default']
    SubTitle: typeof import('./components/Title/src/SubTitle.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    TagBox: typeof import('./components/Sidebar/src/TagBox.vue')['default']
    TagItem: typeof import('./components/Tag/src/TagItem.vue')['default']
    TagList: typeof import('./components/Tag/src/TagList.vue')['default']
    ThemeToggle: typeof import('./components/ToggleSwitch/ThemeToggle.vue')['default']
    Title: typeof import('./components/Title/src/Title.vue')['default']
    Toggle: typeof import('./components/ToggleSwitch/Toggle.vue')['default']
    UserCenter: typeof import('./components/UserCenter.vue')['default']
    WebsiteInfo: typeof import('./components/Sidebar/src/WebsiteInfo.vue')['default']
  }
}
